# Note: Remove the baseurl in order to deploy at the domain root
baseurl: 
title: bitbear
# Whether the header (with large title and subtitle) should be displayed
header: false
subtitle: 
author: bitbear
description: 
show_author: false
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /blog/:categories/:slug
timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
